% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Feb-2019 20:37:32
%  MATLAB version: 9.3.0.948333 (R2017b) Update 9
% -------------------------------------------------------------------
                            

DATA = ...
  [2 7 9 7;
   3 1 5 6;
   8 1 2 5];

ans = ...
  [2 8 1 9 2 6;
   3 7 1 5 7 5];

DATA' %This command swaps rows with the columns
DATA(:,[1 4]) %This creates a lists only column 1 and 4
reshape(DATA,2,6) %This command recreates the matrix into a 2X6 matrix
DATA(:)%This command takes the original DATA matrix and converts its into a
%single column 
flipud(DATA) %This command swaps the first and last rows with each other
fliplr(DATA)%This command swaps the left and right sides of the matrix 
[DATA; DATA(end,:)] %Copies the last row and make another row
DATA(1:3,:) %Nothing occured to the original DATA matrix
[DATA ; DATA(1:2,:)] %list the matrix and writes row 1 and 2 
sum(DATA') %sums the columns and therefore three values are
sum(DATA,2) %sums the total of each row 
[DATA ; sum(DATA) ] [ sum(DATA,2) ; sum(DATA(:)) ] ]
%List the matrix and sums of each row and columns and the diagonals. These values are created and placed into rest matrix.    